"""DB delete one ficha

Revision ID: 108a63169e29
Revises: 51841a9d3b23
Create Date: 2023-04-18 01:34:53.048348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '108a63169e29'
down_revision = '51841a9d3b23'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
