"""DB delete one 

Revision ID: 51841a9d3b23
Revises: beb9c3aa9f2c
Create Date: 2023-04-18 01:33:54.904502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51841a9d3b23'
down_revision = 'beb9c3aa9f2c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
