version: '3.11'

services:
  
  db:
    image: postgres
    environment:
      - POSTGRES_DB=tz_3_db
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5501:5432"
    healthcheck :
      test: [ "CMD", "pg_isready", "-q", "-d", "tz_3_db", "-U", "postgres" ]
      interval : 5s
      timeout : 5s
      retries : 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_SERVICE=postgres
      - TEST_POSTGRES_DB=db_test
    depends_on:
      db:
        condition: service_healthy
