version: '3.11'

services:
  python:
    build: .
    depends_on:
      db_auth:
        condition: service_healthy


  db_auth:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 5s
        timeout: 5s
        retries: 5