version: '3.11'

services:
  app:
      build:
        context: .
        dockerfile: Dockerfile
      env_file:
        - app/.env
      ports:
      - "8000:8000"
      depends_on:
        db:
          condition: service_healthy
        

  db:
    image: postgres
    env_file:
      - ./app/.env
    ports:
      - "5432:5432"
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 5s
        timeout: 5s
        retries: 5