"""DB init

Revision ID: 418b05f9ea54
Revises: fc7bce0692c4
Create Date: 2023-04-11 19:05:03.520037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '418b05f9ea54'
down_revision = 'fc7bce0692c4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subtask', sa.Column('task_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'subtask', 'task', ['task_id'], ['id'])
    op.drop_constraint('task_subtask_id_fkey', 'task', type_='foreignkey')
    op.drop_column('task', 'subtask_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('subtask_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('task_subtask_id_fkey', 'task', 'subtask', ['subtask_id'], ['id'])
    op.drop_constraint(None, 'subtask', type_='foreignkey')
    op.drop_column('subtask', 'task_id')
    # ### end Alembic commands ###
